### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by adibaba** [dice-group/nbgraderutils#9]
The validation button always produces a message:
Success! Your notebook passes all the tests.
Even when an Exception is thrown.

**Comment by adibaba** [comment]
Exception issues may concern the iJava kernel.
Maybe related to #8 Manual grading after interrupted kernel.

**Comment by adibaba** [comment]
Notes:

Make sure, the validation extension is enabled:
```
# jupyter nbextension list
Known nbextensions:
  config dir: /opt/conda/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      create_assignment/main disabled
      validate_assignment/main  enabled 
      - Validating: OK
    tree section
      formgrader/main disabled
      assignment_list/main  enabled 
      - Validating: OK
```

Ensure the exercise throws an exception on failed tests:

```java
int[] toNumericAscii(String string) {
    int[] result = new int[string.length()];

    // YOUR CODE HERE

    return result;
}
```
```java
%maven org.junit.jupiter:junit-jupiter-api:5.3.1
import org.junit.jupiter.api.Assertions;
import org.opentest4j.AssertionFailedError;

Assertions.assertArrayEquals( new int[]{ 72, 105 }, toNumericAscii("Hi") );
Assertions.assertEquals(72, toNumericAscii("Hi")[0], "character 'H'");
Assertions.assertTrue(105 == toNumericAscii("Hi")[1], "character 'i'");
System.out.println("Test(s) successfully completed.");
```
```
---------------------------------------------------------------------------
org.opentest4j.AssertionFailedError: array contents differ at index [0], expected: <72> but was: <0>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.AssertArrayEquals.failArraysNotEqual(AssertArrayEquals.java:432)
	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:244)
	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:90)
	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:86)
	at org.junit.jupiter.api.Assertions.assertArrayEquals(Assertions.java:644)
	at .(#24:1)
```

On click on the validation-button, it states:

> Success! Your notebook passes all the tests.

**Comment by adibaba** [comment]
Removed disabling validation extension in https://github.com/dice-group/nbgraderutils/commit/6c09a229c1a8de725283c0532eb7b02f53d34b59
